### ISSUE TITLE
SUPPRESS_NO_CONFIG_WARNING in the environment.

### ISSUE THREAD

**Issue by yustarandomname** [lpshanley/routify-starter-firebase#3]
when running ```npm run dev``` the terminal throws 
```WARNING: No configurations found in configuration directory:/[GitHub path]/routify-starter-firebase/config ``` 
```WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.```

<img width="550" alt="Screenshot 2020-06-02 at 13 20 11" src="https://user-images.githubusercontent.com/25432790/83514358-cc3fa800-a4d3-11ea-9dee-2273fc0abe8c.png">

**Comment by lpshanley** [comment]
If this is the log from the start it would seem that a few steps were missed in your setup. 

You need to run `npm i` in the main directory and in the functions directory.

Please also make sure you edit the `.firebaserc` file with your projects id to get going. After this you should be up and running!
